# render.yaml
services:
  - type: web
    name: ecommerce-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DB_HOST
        value: gateway01.eu-central-1.prod.aws.tidbcloud.com
      - key: DB_USER
        value: 3MQF71BGR4igtWy.root
      - key: DB_PASSWORD
        value: 42MeRZKaKyT1Fk1z
      - key: DB_NAME
        value: test
      - key: DB_PORT
        value: 4000
      - key: JWT_SECRET
        value: h3jdKcCKUTg1lt037JhECSIN
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CHAPA_PUBLIC_KEY
        value: CHAPUBK_TEST-LlA4GnzuplVZy51qlRWfRssXp1wFZd6E
      - key: CHAPA_SECRET_KEY
        value: CHASECK_TEST-cKt0OatPOMJK2T1BXvWHX6FzKUyBYJeH
      - key: CHAPA_API_URL
        value: https://api.chapa.co/v1
